# This is a basic workflow to help you get started with Actions

name: printing

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      value:
        description: "Printing the given value"
        required: true
  
jobs:
  printing:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Echo '${{ github.event.inputs.value }}'"
